### ISSUE TITLE
Error when self relaying outdated txs

### ISSUE THREAD

**Issue by arifintahu** [gjermundgaraba/gon-tools#12]
Got this error when self relaying iris -> stargaze
![image](https://user-images.githubusercontent.com/20294658/225873029-46e3de50-373a-4b5b-8eb1-1ae45dbd5036.png)

Then, I removed `panic(err)` on this [line](https://github.com/gjermundgaraba/gon-tools/blob/8ac7f7827d7a8a8c3a28fc53953ac1f5ae30b3f1/gon-cli/gorelayer/rly.go#L165)
and it works fine
![image](https://user-images.githubusercontent.com/20294658/225873525-4cac3bda-1d3a-4c63-b3aa-ecec00ebf465.png)

**Comment by gjermundgaraba** [comment]
Good catch, I think it should not panic there. Will fix this in the next release (due in a few minutes)

**Comment by gjermundgaraba** [comment]
Solved in the latest release. Thanks for letting me know!
