### ISSUE TITLE
Request for the addition of the Nano editor feature

### ISSUE THREAD

**Issue by Dedenwrg** [gjermundgaraba/gon-tools#7]
If possible please add Nano editor I'm not familiar with vi editor, thanks in advance

**Comment by gjermundgaraba** [comment]
Good point. It is actually configurable already, but it is not obvious.

A workaround you can do right now is to set the `EDITOR` environment variable to nano, or simply call the cli like this:
```bash
$ EDITOR=nano gon
```

I'll update the README with this info, but do you have any other ideas on how this might work better? I am not sure I want nano to be the default, but I would love to make it more easily configurable.

**Comment by Dedenwrg** [comment]
Thank you very much for responding to my request
